# MongoDB Atlas Cloud Database Configuration
spring.data.mongodb.uri=mongodb+srv://hotpot_admin:LauVuong2026@cluster0.e3rgrsr.mongodb.net/lau_vuong_db?retryWrites=true&w=majority&appName=Cluster0

# Server port configuration
server.port=8081
